### ISSUE TITLE
Feat request: blur old element when performing an action that would focus a new one

### ISSUE THREAD

**Issue by babramczyk** [testing-library/user-event#190]
i.e., you're focused on an input and then you click a button -- right now, the input never blurs

[![Edit headless-cloud-o3obp](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/headless-cloud-o3obp?fontsize=14&hidenavigation=1&previewwindow=tests&theme=dark)

**Comment by chestozo** [comment]
+1 also was trying to get this behaviour
`fireEvent` from `@testing-library/react` is not providing it too

**Comment by diego-codes** [comment]
Is anyone working on this? I'd love to give it a try!

**Comment by Gpx** [comment]
This should be fixed in the latest version, please give it a try and feel free to comment in this issue if you find other errors

**Comment by babramczyk** [comment]
@Gpx Here is the same codesandbox with `@testing-library/user-event` v10, and it still fails

https://codesandbox.io/s/jolly-banach-eqinq?fontsize=14&hidenavigation=1&theme=dark

If you click the input first before typing, the blur is called twice.

If you don't click the input at all, the blur is never called at all.

**Comment by Gpx** [comment]
The bug appears only if the `input` is a child of `label`, if I use `htmlFor` it works fine. I think we don't handle that case correctly

The bug is probably [here](https://github.com/testing-library/user-event/blob/1af67066f57377c5ab758a1215711dddabad2d83/src/index.js#L26-L29), it needs more investigation

**Comment by kentcdodds** [comment]
I think this was fixed a few versions ago. Please let us know if this is still an issue.
