### ISSUE TITLE
Test fails when using userEvent.type for an input element of type 'number' 

### ISSUE THREAD

**Issue by tsairinius** [testing-library/user-event#411]
Hello, I recently updated the versions for the following dependencies, and I'm now encountering an issue when using userEvent.type to type a number: 
    "@testing-library/jest-dom": "^5.11.1",     // Used to be 4.2.4
    "@testing-library/react": "^10.4.7",          // Used to be 9.5.0
    "@testing-library/user-event": "^12.0.13",     //Used to be 11.4.2

Here are all of the dependencies in my project: 
    "@testing-library/jest-dom": "^5.11.1",
    "@testing-library/react": "^10.4.7",
    "@testing-library/user-event": "^12.0.13",
    "prop-types": "^15.7.2",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-scripts": "3.4.1",
    "react-test-renderer": "^16.13.1"

Here's the test that is failing: 
```
let mockCallback;
beforeEach(() => {
  mockCallback = jest.fn();
  render(<CreateProfileForm label='+' callback={mockCallback}/>);
});

it('weight input gets updated as user types in weight', async () => {
  const weightInput = screen.getByLabelText('Weight(lb)');
  await userEvent.type(weightInput, '200');
  expect(weightInput).toHaveAttribute('value', '200');
});
```

The test fails because the weight input box was not updated: 
```
    expect(element).toHaveAttribute("value", "200") // element.getAttribute("value") === "200"

    Expected the element to have attribute:
      value="200"
    Received:
      value=""

      38 |   const weightInput = screen.getByLabelText('Weight(lb)');
      39 |   await userEvent.type(weightInput, '200');
    > 40 |   expect(weightInput).toHaveAttribute('value', '200');
         |                       ^
      41 | });
```

The 'weightInput' element is of type 'number'. The issue however, does not occur when using userEvent.type for an input of type 'text'.

**Comment by maxnewlands** [comment]
@tsairinius I wonder if this is a result of the fact that `value` as a content attribute (`input.getAttribute('value')`) doesn't reflect `value` as an IDL attribute (`input.value`). (More on the distinction [here](https://stackoverflow.com/a/6004028)). 

I don't know what your `CreateProfileForm` component looks like, but [in my testing](https://codesandbox.io/s/trusting-bash-m5qqr?file=/src/__tests__/index.js), I can't see the `toHaveAttribute` matcher working with either `type=text` or `type=number`. However, if I use `expect(input.value).toBe(...)` or `expect(input).toHaveValue(...)`, tests pass as expected. 

Is that consistent with what you see? If so, perhaps the documentation of `toHaveAttribute` could be clearer about this point?

**Comment by tsairinius** [comment]
@maxnewlands For my implementation, I did not have issues calling `toHaveAttribute` when the input's type was set to 'text'. This might be due to the fact that my `CreateProfileForm` is a controlled form, so the input's value is determined by the form's state. I pasted my component here in Codesandbox: [https://codesandbox.io/s/upbeat-sun-wu81l?file=/src/CreateProfileForm.js](url). Sorry, not too familiar with Codesandbox, so the test on there isn't passing for some unknown reason. 

If I no longer made the weight input controlled, I did find that running the test (using `toHaveAttribute`) locally led to a failure, where the input's value resulted in `null`. Changing to `expect(input.value).toBe(...)` or `expect(input).toHaveValue(...)` fixed the issue.

And using either of those alternative approaches also allowed the test to pass when the input was `type=number` (regardless of whether the input was controlled). 

In all, the issue does seem to be as you suggest: value as a content attribute (`input.getAttribute('value')`) doesn't reflect value as an IDL attribute (`input.value`). However, this test only started failing after I updated my dependencies. So I'm not sure if clarifying the `toHaveAttribute` documentation is sufficient or if further investigation is needed.

**Comment by jerryfishzz** [comment]
I do have the same issue as @tsairinius described: the input element of type "number" won't update, but can work if the element type is "text". This problem will happen in the latest package version:

"@testing-library/jest-dom": "^5.11.4",
"@testing-library/react": "^11.0.2",
"@testing-library/user-event": "^12.1.4", 

It works without problems under old version:
"@testing-library/jest-dom": "^4.2.4",
"@testing-library/react": "^9.3.2",
"@testing-library/user-event": "^7.1.2",

The test contents:

```javascript
// src/favorite-number.js
import React from "react";

function FavoriteNumber({ min = 1, max = 9 }) {
  const [number, setNumber] = React.useState(0);
  const [numberEntered, setNumberEntered] = React.useState(false);
  function handleChange(event) {
    setNumber(Number(event.target.value));
    setNumberEntered(true);
  }
  const isValid = !numberEntered || (number >= min && number <= max);
  return (
    <div>
      <label htmlFor="favorite-number">Favorite Number</label>
      <input
        id="favorite-number"
        type="number"
        value={number}
        onChange={handleChange}
      />
      {isValid ? null : <div role="alert">The number is invalid</div>}
    </div>
  );
}

export { FavoriteNumber };
```

```javascript
// src/__tests__/state.js
import React from "react";
import { render, fireEvent } from "@testing-library/react";
import { FavoriteNumber } from "../favorite-number";
import userEvent from "@testing-library/user-event";

test("entering an invalid value shows an error message", () => {
  const { getByLabelText, getByRole, debug, rerender } = render(
    <FavoriteNumber />
  );
  const input = getByLabelText(/favorite number/i);
  // fireEvent.change(input, { target: { value: "10" } });
  userEvent.type(input, "10");
  debug();
  expect(getByRole("alert")).toHaveTextContent(/the number is invalid/i);
  rerender(<FavoriteNumber max={10} />);
  debug();
});
```

Here is the repo with the issue under the latest package version: https://github.com/jerryfishzz/react-testing-latest-env

My test is a little different from the issue reporter, but the logic is the same. I just use `debug()` to show the DOM state then I find the input value does not update but show `0`. Note, I also use `fireEvent` (I commented off) to do the similar test. It works fine in both latest and old versions.

I tried to upload it to code sandbox to share more easily with others but looks like code sandbox doesn't support the latest package very well and leads to an unknown error for testing, just as @tsairinius said again: ) BTW, The old version can run properly on code sandbox. But since it has no testing problem, no need to post here.

**Comment by marcosvega91** [comment]
Hi @jerryfishzz, I have tried and the value will change when `change` event will be  triggered. The `change` event is triggered after `blur` but `type` function will not handle these events.

**Comment by jerryfishzz** [comment]
Hi @marcosvega91, sorry, probably I didn't make myself clearly. The component `favorite-number.js` can always run properly. What I said "the input element of type `number` won't update" is the result in testing.

I use `userEvent.type()` to simulate the event `change` that happens in the component. This was what I did in the old version and worked:

"@testing-library/jest-dom": "^4.2.4",
"@testing-library/react": "^9.3.2",
"@testing-library/user-event": "^7.1.2",

So I thought it should work too in the latest version:

"@testing-library/jest-dom": "^5.11.4",
"@testing-library/react": "^11.0.2",
"@testing-library/user-event": "^12.1.4",

But now it looks like it can't work properly as I expected.

**Comment by robertaird** [comment]
I ran into this same issue, and managed to get it working by setting `{ delay: 1 }` as the third argument. Probably not ideal, but it'll do for now

**Comment by jerryfishzz** [comment]
> 
> 
> I ran into this same issue, and managed to get it working by setting `{ delay: 1 }` as the third argument. Probably not ideal, but it'll do for now

I thought maybe we should use fireEvent before this bug is solved

**Comment by ph-fritsche** [comment]
@jerryfishzz This is no bug in `userEvent.type()`
`<input type='number'/>` does not trigger a `change` event while typing. There might have been a bug in the earlier version.

If you want to update when typing happens, you should listen to the `input` event.

Or if you don't want the callback to be triggered on typing, but explicitly on the `change` event:
> The `change` event is triggered after `blur` but `type` function is not handling these events.

**Comment by nickmccurdy** [comment]
Should this be closed, or is a code/documentation update still necessary?

**Comment by ph-fritsche** [comment]
[Specification](https://html.spec.whatwg.org/multipage/input.html#common-input-element-events) and [MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/change_event) are very clear about when the `change` event will be triggered.

React facilitates attaching an event handler by creating [Synthetic](https://reactjs.org/docs/events.html#form-events) `change` and `input` events when `input` happens in the DOM. Therefore attaching the callback via `<input onChange={handleWhatIsInputInTheDom}/>` works.

Some third-party libraries attach their handlers directly in the DOM themselves and some users get confused.

I imported the test [shared by](https://github.com/jerryfishzz/react-testing-latest-env) @jerryfishzz [on Codesandbox](https://codesandbox.io/s/goofy-banach-uq36w). It works just fine as the handler is passed per `onChange` prop.
No idea why it was failing for him.

The original issue seems to be resolved by correcting the test to examine the property instead of the attribute.

@robertaird's solution with `delay` probably covered an unrelated problem with deferred update per `Promise` or `setTimeout`.

**Comment by fgs-dbudwin** [comment]
@ph-fritsche could you elaborate on this, maybe with an example:

>If you want to update when typing happens, you should listen to the input event.

I have a test where the current page changes based on what the user entered into a `<input type="number">` box.

If I call the following, it _will_ trigger the `onChange` function attached to my `input` (based on the `console.log` I put in there), but nothing seems happen, my test still fails.  My test tries to verify the content displayed in the page according to the given page number.
```js
userEvent.type(goToPageInput, "2");
...
expect("I'm on page 2").toBeInTheDocument();
```

My test do pass if I use `fireEvent` instead.
```js
fireEvent.change(goToPageInput, {
    target: { value: 2}
});
```

I tried to put my `expect` in a `waitFor` and I also tried to use the `{ delay: 1 }` trick mentioned above, no luck.

**Comment by ph-fritsche** [comment]
> @ph-fritsche could you elaborate on this, maybe with an example:
> > If you want to update when typing happens, you should listen to the input event.

https://codesandbox.io/s/intelligent-saha-ujhnj?file=/src/type.test.js
The reason is explained in [the post above](https://github.com/testing-library/user-event/issues/411#issuecomment-727208713).

If you want to get help on your component or test, please don't let everybody guess what your code might look like. Break it down to a minimal working example and share it on [codesandbox](https://codesandbox.io/) or another platform.
(Most questions tend to solve themselves when broken down enough. :wink: )

**Comment by fgs-dbudwin** [comment]
@ph-fritsche here is a CodeSandbox that more accurately reflects my situation: https://codesandbox.io/s/blazing-flower-02bni?file=/src/App.test.js

There are two tests written the "same" way, one uses `userEvent`, the other ` fireEvent`.  The `userEvent` test does not pass while the `fireEvent` test does.

**Comment by ph-fritsche** [comment]
```js
    // src/App.test.js line 18 is:
    userEvent.type(screen.getAllByTestId("input"), "123");
    // should be: 
    userEvent.type(screen.getByTestId("input"), "3");
    // screen.getAllByTestId returns an array of elements - but you have to supply a single element
    // if you don't apply the changes, typing "123" with the current value of "12" will trigger the input event with '121', '122' and '123'

    // line 21 is:
    expect(mockFnToCall).toHaveBeenCalledWith(newValue);
    // should be:
    expect(mockFnToCall).toHaveBeenCalledWith(123);
    // can not be 17 when entering '123'
```
fixed it

**Comment by maariyadiminsky** [comment]
@kentcdodds Correct me if I'm wrong but `userEvent` still does not handle `onChange`. For example, I have a input with type `number` and `userEvent.click` wouldn't work for me. I had to resort to using `fireEvent`. 

`userEvent` uses `fireEvent` under the code, yet I don't see any `fireEvent.change` within `userEvent` when checking the code. Will there be an update supporting this or maybe I'm just not seeing another way to use `userEvent`? 

I'm my case I'm using `findByLabelText` but I've also tested with `getByLabelText` as shown [here](https://codesandbox.io/s/great-varahamihira-7i0f2?file=/src/FavoriteNumber.test.js), yet it still doesn't work.

This is what I have for now, but it would be great to use `userEvent` instead as I'm using it everywhere else.

```
const newEvent = {
 ...someDateHere,
  price: 70
};

const priceInput = await findByLabelText('Price');

// doesn't work, a float is expected in Apollo. I wonder if this is related.
// errors is result = ""
// userEvent.type(priceInput, newEvent.price); 

fireEvent.change(priceInput, { target: { value: newEvent.price }}); // works perfect
expect(priceInput.value).toBe(`${newEvent.price}`);
```

Thanks so much 🙏🏻

**Comment by ph-fritsche** [comment]
> Correct me if I'm wrong but `userEvent` still does not handle `onChange`.

It does handle `onChange`, but not `change`. Explained in the [the post above](https://github.com/testing-library/user-event/issues/411#issuecomment-727208713).

> I'm my case I'm using `findByLabelText` but I've also tested with `getByLabelText` as shown [here](https://codesandbox.io/s/great-varahamihira-7i0f2?file=/src/FavoriteNumber.test.js), yet it still doesn't work.

Your test IS working :confused: 

`v14` also tracks the initial value and automatically triggers the `change` event when an element loses focus if the value has changed.

**Comment by leochoo** [comment]
This is happening to me too. It will take me a long time to make a minimum example that reproduces this, but I can fetch and type default values for all data except for just one field in the form! And it works when it is "text" but fails when it's a number!!

**Comment by erickbelfy** [comment]
Im having the same issue, with a given form:
```
 <div
                    class="MuiBox-root MuiBox-root-10 makeStyles-formField-8"
                  >
                    <div
                      class="MuiBox-root MuiBox-root-11"
                    >
                      <label
                        class="makeStyles-root-12 makeStyles-root-13 makeStyles-formFieldLabelRoot-9"
                        for="Account name"
                      >
                        Account name
                      </label>
                      <div
                        class="MuiBox-root MuiBox-root-14"
                      >
                        <div
                          class="MuiInputBase-root OSSTextInput-statusPrimary-15 MuiInputBase-fullWidth Mui-focused"
                        >
                          <input
                            aria-describedby="Account name--helperText"
                            autocomplete="off"
                            class="MuiInputBase-input"
                            data-testid="accountNameField"
                            id="Account name"
                            maxlength="255"
                            name="accountName"
                            placeholder="Ex: Acme Inc."
                            type="text"
                            value=""
                          />
                        </div>
                      </div>
                    </div>
```
doing the following test:
```
import { render, fireEvent, screen, within, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import React from 'react';

const user = userEvent.setup();
render(getComponent(props));
const accountName = screen.getByTestId('accountNameField');
await user.type(accountName, 'foo');
    await waitFor(() => {
      expect(screen.getByTestId('accountNameField')).toHaveText('foo');
    });
```

is not working properly

**Comment by dagadbm** [comment]
i have the same issue with pasword field (using ant design)
Other fields it works perfectly.

**Comment by challet** [comment]
Any summary about the issue and a possible workaround ?
I have the or close problem : typing into a number input works well on each keypress, until a blur event occurs and then the value is flushed to an empty string.
